
GET http://localhost:3000/api/memo

###

POST http://localhost:3000/api/memo
Content-Type: application/json

{
  "title": "이걸로 하면",
  "content": "괜찮은데 왜 뭐가 문제야"
}

###

GET http://localhost:3000/api/memo/66508fc8f399ed78acfae9e0