
GET https://codeit-weekly-mission.vercel.app/api/memo

###

GET http://localhost:3000/memo

###

POST https://codeit-weekly-mission.vercel.app/api/memo
Content-Type: application/json

{
  "title": "이걸로 하면",
  "content": "괜찮은데 왜 뭐가 문제야"
}

###

GET http://localhost:3000/memo